### ISSUE TITLE
Example: Crash on Xcode 11 beta 5?

### ISSUE THREAD

**Issue by karolkulesza** [phimage/morphi#1]
Hi there,

Does it crash on your side on Xcode 11 beta 5 ? See the following, when I try to run the Example app:

<img width="1512" alt="Screen Shot 2019-08-15 at 3 09 13 PM" src="https://user-images.githubusercontent.com/2694531/63096840-3a2fd880-bf6f-11e9-8cd7-d12b54386392.png">

**Comment by phimage** [comment]
I see. This beta 5 was crappy.
beta 6 fix it
